homepage: "https://postgresql.org"
primary_contact: "sfrost@snowman.net"
language: c
auto_ccs :
  - "ouyangyunshu@google.com"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
  - address
  - undefined
